version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  ApplicationStop:  # Stop running application first
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ubuntu

  BeforeInstall:  # Then, install dependencies and set up environment
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ubuntu
