version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running Linting..."
      - npx eslint .
      - echo "Running Tests..."
      - npm test
  build:
    commands:
      - echo "Build Successful!"
  post_build:
    commands:
      - echo "Triggering AWS CodeDeploy..."
      - aws deploy create-deployment \
        --application-name MyApp \
        --deployment-group-name MyDeploymentGroup \
        --github-location repository-name:main
