version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running Pre-Build Steps..."
      
  build:
    commands:
      - echo "Building Application..."
      - echo "Running Linting..."
      # - npm run lint
      - echo "Running Tests..."
      - npm test

  post_build:
    commands:
      - echo "Build Completed Successfully."

artifacts:
  files:
    - '**/*'
